title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ashishkin21.github.io/olimnotes.github.io

aux_links:
  Template Repository: https://github.com/ashishkin21/olimnotes.github.io
